# Generated by Django 3.0.3 on 2020-02-23 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0002_auto_20200223_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
